GET http://localhost:3001/api/producers
Content-Type: application/json

###

POST http://localhost:3001/api/producers
Content-Type: application/json

{
  "name": "Julian",
  "documentType": "CPF",
  "documentNumber" "065"
}